server:
  port: 8010
management:
  endpoint:
    health:
      show-details: always
# INFO ENDPOINT CONFIGURATION
info:
  app:
    name: microservice-consumer-movie-ribbon
    description: Demo project for Spring Boot
    version: 0.0.1-SNAPSHOT
    encoding: UTF-8
    java:
      version: 1.8.0_131
user:
  userServiceUrl: http://microservice-provider-user/
# eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: microservice-consumer-movie
